title:              Pastimes Blog
email:              dushko.dushanoski@gmail.com
description:        A Walk On The Other Side Of The Mirror
author:             Dushko Dushanoski
baseurl:            "/blog"
url:                "https://dule-dushanoski.github.io"

# Social Profiles
twitter_username:   dushko100
github_username:    dule-dushanoski
facebook_username:  dusko.dusanoski
instagram_username: dule100
linkedin_username:  dushko-dushanoski-94a7b089

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
